### ISSUE TITLE
how do you enable script compatibility mode on violent monkey 

### ISSUE THREAD

**Issue by Cxsmo-ai** [Ceiridge/omeglemitm#3]
how do you enable script compatibility mode on violentmonkey

**Comment by Ceiridge** [comment]
This feature does not exist on ViolentMonkey. Perhaps it is not needed.

**Comment by Cxsmo-ai** [comment]
when i have the script enabled it just keeps reloading this screen even though i logged in 
![image](https://github.com/Ceiridge/omeglemitm/assets/74084396/b32cc764-7934-4d4b-907a-c809048e7000)

**Comment by Ceiridge** [comment]
Also note that this script is not working on any stranger video chat at the moment, as Omegle has shut down.

**Comment by Ceiridge** [comment]
> when i have the script enabled it just keeps reloading this screen even though i logged in ![image](https://user-images.githubusercontent.com/74084396/282659567-b32cc764-7934-4d4b-907a-c809048e7000.png)

1. The script does not work on ome or any other site currently
2. You have to open `ome.tv/robots.txt` to get the UI
