### ISSUE TITLE
interface on ometv 

### ISSUE THREAD

**Issue by miou99** [Ceiridge/omeglemitm#8]
![Screenshot 2024-03-06 122107](https://github.com/Ceiridge/omeglemitm/assets/162419499/f561efe1-3504-4a9f-985d-a6ae25f37438)
nothing happend when i press next

**Comment by Ceiridge** [comment]
Please read the following section: https://github.com/Ceiridge/omeglemitm?tab=readme-ov-file#current-situation
This behavior is expected.

I published this tool after the shutdown of Omegle and I never adapted it fully to Ome or other websites. This repo exists mostly for archival purposes. It is not to be used.

**Comment by miou99** [comment]
Oh,ok
thanks great work you are doing here 
waiting for ometv complete
